version: 2.1

orbs:
  linter: reactioncommerce/linter@0.0.1

jobs:
  megalinter:
    docker:
      - image: circleci/python:3.9
        environment:
          ENABLE: DOCKERFILE,MARKDOWN,YAML
          SHOW_ELAPSED_TIME: "true"
    working_directory: /tmp/workspace
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          version: 20.10.7     
          docker_layer_caching: true    
      - run:
          name: Install Node.js
          command: |
            curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs          
      - run:
          name: Install Mega-Linter
          command: |
           sudo npm install -g mega-linter-runner

      - run:
          name: Update Docker daemon configuration
          command: |
            echo 'export DOCKER_CLI_EXPERIMENTAL=enabled' >> $BASH_ENV
            source $BASH_ENV           

      - run:
          name: Run MegaLinter
          command: |
            npx mega-linter-runner -e "ENABLE=DOCKERFILE,MARKDOWN,YAML" -e "SHOW_ELAPSED_TIME=true"
   
  post:
   docker:
      - image: oxsecurity/megalinter:v6
   steps:
      - store_artifacts:
          path: mega-linter.log
          destination: artifacts
      - store_artifacts:
          path: megalinter-reports
          destination: artifacts
            
           
workflows:
  version: 2
  sonar-report:
    jobs:
      - megalinter

